main =
  print "1"
  print . try $ throw Error
  print "2"

